workflows:
  android-prod:
    name: Android prod
    instance_type: linux_x2
    max_build_duration: 60
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: production
          include: true
          source: true
      cancel_previous_builds: true
    environment:
      groups:
        - google_credentials
      vars:
        FIREBASE_PROJECT: "icoc-8f075"
      flutter: stable
      java: 17
    scripts:
      - name: Set up Android keystore
        script: |
          echo "$KEYSTORE_FILE" | base64 --decode > /tmp/keystore.jks
          cat > "$CM_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$KEYSTORE_PASSWORD
          keyPassword=$KEYSTORE_KEY_PASSWORD
          keyAlias=key2020
          storeFile=/tmp/keystore.jks
          EOF
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release --dart-define=openAIKey=$openAIKey
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT
        track: production
