// Mocks generated by Mockito 5.4.6 from annotations
// in icoc/test/presentation/bloc/insights_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:icoc/core/errors/failures.dart' as _i5;
import 'package:icoc/core/user_languages.dart' as _i7;
import 'package:icoc/domain/model/insights/post.dart' as _i6;
import 'package:icoc/domain/repository/insights_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [InsightsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInsightsRepository extends _i1.Mock
    implements _i3.InsightsRepository {
  MockInsightsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Post>>> getPosts(
          {Set<String>? languages}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPosts,
          [],
          {#languages: languages},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Post>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Post>>(
          this,
          Invocation.method(
            #getPosts,
            [],
            {#languages: languages},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Post>>>);
}

/// A class which mocks [InsightsUserLanguagesHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockInsightsUserLanguagesHandler extends _i1.Mock
    implements _i7.InsightsUserLanguagesHandler {
  MockInsightsUserLanguagesHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> get languages => (super.noSuchMethod(
        Invocation.getter(#languages),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String get firstActiveLang => (super.noSuchMethod(
        Invocation.getter(#firstActiveLang),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#firstActiveLang),
        ),
      ) as String);

  @override
  set languages(Map<String, dynamic>? _languages) => super.noSuchMethod(
        Invocation.setter(
          #languages,
          _languages,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> addLanguage(
    String? lang,
    bool? isActive,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addLanguage,
          [
            lang,
            isActive,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateLanguage(
    String? lang,
    bool? isActive,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLanguage,
          [
            lang,
            isActive,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveAllLanguages(Map<String, dynamic>? updatedLanguages) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAllLanguages,
          [updatedLanguages],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  bool containsLang(String? lang) => (super.noSuchMethod(
        Invocation.method(
          #containsLang,
          [lang],
        ),
        returnValue: false,
      ) as bool);

  @override
  Set<String> getActiveLanguages() => (super.noSuchMethod(
        Invocation.method(
          #getActiveLanguages,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);
}
