// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC80HYwa2V8gEsXRwQdbXS8Jwn3vJ6hd8o',
    appId: '1:423282730331:android:fc18e804352af8161ce67e',
    messagingSenderId: '423282730331',
    projectId: 'icoc-8f075',
    databaseURL: 'https://icoc-8f075.firebaseio.com',
    storageBucket: 'icoc-8f075.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp77YITl5X6jJDGtEyKlEQudR_VxL68J4',
    appId: '1:423282730331:ios:39a8b51e8b8fc33a1ce67e',
    messagingSenderId: '423282730331',
    projectId: 'icoc-8f075',
    databaseURL: 'https://icoc-8f075.firebaseio.com',
    storageBucket: 'icoc-8f075.appspot.com',
    androidClientId: '423282730331-3btuoc3hg8ovklvk84fkp36744eo07c6.apps.googleusercontent.com',
    iosClientId: '423282730331-5d1r23tp68fpitvjnb04i9a78jh44sd1.apps.googleusercontent.com',
    iosBundleId: 'com.icoc.projects',
  );
}
