import 'package:icoc/constants.dart';

const languagesToEnumMap = {
  'en': Languages.en,
  'et': Languages.et,
  'fr': Languages.fr,
  'de': Languages.de,
  'bg': Languages.bg,
  'it': Languages.it,
  'lv': Languages.lv,
  'lt': Languages.lt,
  'no': Languages.no,
  'pl': Languages.pl,
  'ro': Languages.ro,
  'ru': Languages.ru,
  'es': Languages.es,
  'sv': Languages.sv,
  'uk': Languages.uk,
  'sk': Languages.sk,
  'sl': Languages.sl,
  'fi': Languages.fi,
  'sq': Languages.sq,
  'eu': Languages.eu,
  'be': Languages.be,
  'bs': Languages.bs,
  'ca': Languages.ca,
  'hr': Languages.hr,
  'cs': Languages.cs,
  'da': Languages.da,
  'nl': Languages.nl,
  'el': Languages.el,
  'hu': Languages.hu,
  'ga': Languages.ga,
  'lb': Languages.lb,
  'mk': Languages.mk,
  'pt': Languages.pt,
  'sr': Languages.sr,
};
