import 'package:icoc/core/constants.dart';

Languages convertLanguagesEnum(String languageCode) {
  switch (languageCode) {
    case 'et':
      return Languages.et;
    case 'fr':
      return Languages.fr;
    case 'de':
      return Languages.de;
    case 'bg':
      return Languages.bg;
    case 'it':
      return Languages.it;
    case 'lv':
      return Languages.lv;
    case 'lt':
      return Languages.lt;
    case 'no':
      return Languages.no;
    case 'pl':
      return Languages.pl;
    case 'ro':
      return Languages.ro;
    case 'ru':
      return Languages.ru;
    case 'es':
      return Languages.es;
    case 'sv':
      return Languages.sv;
    case 'uk':
      return Languages.uk;
    case 'sk':
      return Languages.sk;
    case 'sl':
      return Languages.sl;
    case 'fi':
      return Languages.fi;
    case 'sq':
      return Languages.sq;
    case 'eu':
      return Languages.eu;
    case 'be':
      return Languages.be;
    case 'bs':
      return Languages.bs;
    case 'ca':
      return Languages.ca;
    case 'hr':
      return Languages.hr;
    case 'cs':
      return Languages.cs;
    case 'da':
      return Languages.da;
    case 'nl':
      return Languages.nl;
    case 'el':
      return Languages.el;
    case 'hu':
      return Languages.hu;
    case 'ga':
      return Languages.ga;
    case 'lb':
      return Languages.lb;
    case 'mk':
      return Languages.mk;
    case 'pt':
      return Languages.pt;
    case 'sr':
      return Languages.sr;
    default:
      return Languages.en;
  }
}
